### ISSUE TITLE
Please install the supplied AppData file

### ISSUE THREAD

**Issue by hughsie** [j-jorge/plee-the-bear#2]
Please consider improving and installing this AppData file we wrote: https://raw.githubusercontent.com/hughsie/fedora-appstream/master/appdata-extra/desktop/plee-the-bear.appdata.xml

This is used in GNOME and KDE software installers to add the application description and some screenshots. We'd love to showcase more applications, but without the extra data file we can't. The AppData file needs to be installed to /usr/share/appdata/ on Linux and the basename needs to match the .desktop basename. It would also be great if you could integrate the file with your translation system (e.g. intltool) to make the descriptions translated.

See http://people.freedesktop.org/~hughsient/appdata/ for more details; thanks!

Richard

**Comment by akien-mga** [comment]
Note that the install section in desktop/CMakeLists.txt is now broken, since it tries to install desktop/appdata while the appdata directory is in the root folder. You should probably move ./appdata to desktop/appdata.

**Comment by Mailaender** [comment]
Can you tag a new release? This patch doesn't apply to the 0.7.0 tarball from the website.

**Comment by j-jorge** [comment]
42d8511 should fix this issue. It has been tagged as 0.7.1.
